[package]
name = "dotnetdll"
version = "0.1.0"
authors = ["Nick Clifford <nick@nickclifford.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "0.22.3"
goblin = "0.4.0"
num-traits = "0.2"
num-derive = "0.3"
paste = "1.0.5"
scroll = "0.10.2"
