[package]
name = "dotnetdll"
version = "0.1.0"
authors = ["Nick Clifford <nick@nickclifford.me>"]
edition = "2021"
license = "GPL-3.0+"

[features]
unchecked_indexing = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "dotnetdll-macros",
    "smolasm"
]

[dependencies]
bitfield = "0.13.2"
bitvec = "0.22.3"
dotnetdll-macros = { path = "dotnetdll-macros" }
log = "0.4.14"
num-traits = "0.2"
num-derive = "0.3"
object = { version = "0.28.2", features = ['write'] }
paste = "1.0.5"
scroll = { version = "0.11.0", features = ['derive'] }
scroll-buffer = "0.3.0"
thiserror = "1.0.31"

[dev-dependencies]
env_logger = "0.9.0"
once_cell = "1.16.0"
regex = "1"
tempfile = "3"
