[package]
name = "dotnetdll"
version = "0.0.1"
authors = ["Nick Clifford <nick@nickclifford.me>"]
edition = "2021"
license = "GPL-3.0+"
repository = "https://github.com/nickbclifford/dotnetdll"
keywords = ["c-sharp", "dotnet", "dll", "compiler", "parser"]
description = "A framework for reading and writing .NET metadata files, such as C# library DLLs."

[features]
unchecked_indexing = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "dotnetdll-macros",
    "examples/smolasm"
]

[dependencies]
bitfield = "0.14.0"
bitvec = "1"
dotnetdll-macros = { path = "dotnetdll-macros", version = "0.0.1" }
log = "0.4.14"
num-traits = "0.2"
num-derive = "0.3"
object = { version = "0.30.0", features = ['write'] }
paste = "1.0.5"
scroll = { version = "0.11.0", features = ['derive'] }
scroll-buffer = "0.3.0"
thiserror = "1.0.31"

[dev-dependencies]
env_logger = "0.10.0"
once_cell = "1.16.0"
regex = "1"
tempfile = "3"
