version: "3.9"
services:
  tests:
    build:
      context: .
      cache_from:
        - ghcr.io/nickbclifford/dotnetdll:latest
    image: ghcr.io/nickbclifford/dotnetdll:latest
    volumes:
      - .:/dotnetdll
